### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by aminya**
Uses GitHub Actions for testing and CI

Fixes https://github.com/AuburnSounds/Dplug/issues/519

Here is the example of a running action:
https://github.com/aminya/Dplug/actions/runs/509368824

image

### CODE REVIEW

**Comment by aminya** [comment]
The action I wrote fails because `aeffect` is not found. How can I download this in GitHubActions?

**Comment by 0xEAB** [comment]
Those are generated from the VST2 SDK (which is not publicly available)

**Comment by p0nce** [comment]
For Azure CI, it has to be decrypted from secrets-for-ci.tar.enc
I think you can just avoid building VST2

**Comment by aminya** [comment]
> For Azure CI, it has to be decrypted from secrets-for-ci.tar.enc
> I think you can just avoid building VST2 (and testing them) as workaround.
> We can get that back later on.

Process can't be installed without AEffect.

```d
Fetching gfm 8.0.5 (getting selected version)...
Fetching wave-d 1.0.7 (getting selected version)...
Performing "debug" build using C:\hostedtoolcache\windows\dc\ldc2-1.24.0\x64\ldc2-1.24.0-windows-multilib\bin\ldc2.exe for x86_64.
arsd-official:characterencodings 4.4.1: building configuration "library"...
arsd-official:dom 4.4.1: building configuration "library"...
intel-intrinsics 1.3.8: building configuration "library"...
dplug:core 10.1.0+commit.7.g6290d9e8: building configuration "library"...
dplug:client 10.1.0+commit.7.g6290d9e8: building configuration "library"...
dplug:vst 10.1.0+commit.7.g6290d9e8: building configuration "library"...
..\..\vst\dplug\vst\translatesdk.d(14,42): Error: file `"aeffect.h"` cannot be found or not in a path specified with `-J`
..\..\vst\dplug\vst\translatesdk.d(14,42):        Path(s) searched (as provided by `-J`):
..\..\vst\dplug\vst\translatesdk.d(14,42):        [0]: `..\..\VST2_SDK\pluginterfaces\vst2.x` (path not found)
..\..\vst\dplug\vst\translatesdk.d(14,64): Error: file `"aeffectx.h"` cannot be found or not in a path specified with `-J`
..\..\vst\dplug\vst\translatesdk.d(14,64):        Path(s) searched (as provided by `-J`):
..\..\vst\dplug\vst\translatesdk.d(14,64):        [0]: `..\..\VST2_SDK\pluginterfaces\vst2.x` (path not found)
..\..\vst\dplug\vst\client.d(135,13): Error: undefined identifier `AEffect`, did you mean variable `_effect`?
..\..\vst\dplug\vst\client.d(137,5): Error: undefined identifier `HostCallbackFunction`
..\..\vst\dplug\vst\client.d(317,11): Error: undefined identifier `ERect`
..\..\vst\dplug\vst\client.d(360,21): Error: undefined identifier `VstIntPtr`
..\..\vst\dplug\vst\client.d(1036,15): Error: undefined identifier `VstIntPtr`
..\..\vst\dplug\vst\client.d(1036,15): Error: undefined identifier `AEffect`
..\..\vst\dplug\vst\client.d(1066,10): Error: undefined identifier `AEffect`
..\..\vst\dplug\vst\client.d(1076,10): Error: undefined identifier `AEffect`
..\..\vst\dplug\vst\client.d(1086,10): Error: undefined identifier `AEffect`
..\..\vst\dplug\vst\client.d(1096,10): Error: undefined identifier `AEffect`
..\..\vst\dplug\vst\client.d(1111,11): Error: undefined identifier `AEffect`
..\..\vst\dplug\vst\client.d(1136,5): Error: undefined identifier `HostCallbackFunction`
..\..\vst\dplug\vst\client.d(1136,5): Error: undefined identifier `AEffect`, did you mean variable `_effect`?
..\..\vst\dplug\vst\client.d(1252,14): Error: undefined identifier `AEffect`, did you mean variable `_effect`?
..\..\vst\dplug\vst\client.d(1253,26): Error: undefined identifier `HostCallbackFunction`
..\..\vst\dplug\vst\client.d(1258,15): Error: undefined identifier `VstIntPtr`
..\..\vst\dplug\vst\client.d(1258,15): Error: undefined identifier `VstInt32`
..\..\vst\dplug\vst\client.d(1258,15): Error: undefined identifier `VstInt32`
C:\hostedtoolcache\windows\dc\ldc2-1.24.0\x64\ldc2-1.24.0-windows-multilib\bin\ldc2.exe failed with exit code 1.

```

**Comment by p0nce** [comment]
https://docs.github.com/en/actions/reference/encrypted-secrets

**Comment by aminya** [comment]
> [docs.github.com/en/actions/reference/encrypted-secrets](https://docs.github.com/en/actions/reference/encrypted-secrets)

There are official download links for older VST3 SDK. I think we can just grab the required files from the official Steinberg link

**Comment by aminya** [comment]
The build now fails with a new error:
https://github.com/aminya/Dplug/runs/1760897362?check_suite_focus=true
```d
Fetching gfm 8.0.5 (getting selected version)...
Fetching wave-d 1.0.7 (getting selected version)...
Performing "debug" build using /opt/hostedtoolcache/dc/ldc2-1.24.0/x64/ldc2-1.24.0-linux-x86_64/bin/ldc2 for x86_64.
arsd-official:characterencodings 4.4.1: building configuration "library"...
arsd-official:dom 4.4.1: building configuration "library"...
intel-intrinsics 1.3.8: building configuration "library"...
dplug:core 10.1.0+commit.8.ga5d3f295: building configuration "library"...
dplug:client 10.1.0+commit.8.ga5d3f295: building configuration "library"...
dplug:vst 10.1.0+commit.8.ga5d3f295: building configuration "library"...
../../vst/dplug/vst/translatesdk.d-mixin-14(126,10): Error: struct `dplug.vst.translatesdk.AEffect` conflicts with struct `dplug.vst.translatesdk.AEffect` at ../../vst/dplug/vst/translatesdk.d-mixin-14(18,10)
../../vst/dplug/vst/translatesdk.d-mixin-14(162,4): Error: enum member `dplug.vst.translatesdk.effFlagsHasEditor` conflicts with enum member `dplug.vst.translatesdk.effFlagsHasEditor` at ../../vst/dplug/vst/translatesdk.d-mixin-14(54,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(163,4): Error: enum member `dplug.vst.translatesdk.effFlagsCanReplacing` conflicts with enum member `dplug.vst.translatesdk.effFlagsCanReplacing` at ../../vst/dplug/vst/translatesdk.d-mixin-14(55,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(164,4): Error: enum member `dplug.vst.translatesdk.effFlagsProgramChunks` conflicts with enum member `dplug.vst.translatesdk.effFlagsProgramChunks` at ../../vst/dplug/vst/translatesdk.d-mixin-14(56,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(165,4): Error: enum member `dplug.vst.translatesdk.effFlagsIsSynth` conflicts with enum member `dplug.vst.translatesdk.effFlagsIsSynth` at ../../vst/dplug/vst/translatesdk.d-mixin-14(57,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(166,4): Error: enum member `dplug.vst.translatesdk.effFlagsNoSoundInStop` conflicts with enum member `dplug.vst.translatesdk.effFlagsNoSoundInStop` at ../../vst/dplug/vst/translatesdk.d-mixin-14(58,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(167,4): Error: enum member `dplug.vst.translatesdk.effFlagsCanDoubleReplacing` conflicts with enum member `dplug.vst.translatesdk.effFlagsCanDoubleReplacing` at ../../vst/dplug/vst/translatesdk.d-mixin-14(59,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(168,4): Error: enum member `dplug.vst.translatesdk.DEPRECATED_effFlagsHasClip` conflicts with enum member `dplug.vst.translatesdk.DEPRECATED_effFlagsHasClip` at ../../vst/dplug/vst/translatesdk.d-mixin-14(60,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(169,4): Error: enum member `dplug.vst.translatesdk.DEPRECATED_effFlagsHasVu` conflicts with enum member `dplug.vst.translatesdk.DEPRECATED_effFlagsHasVu` at ../../vst/dplug/vst/translatesdk.d-mixin-14(61,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(170,4): Error: enum member `dplug.vst.translatesdk.DEPRECATED_effFlagsCanMono` conflicts with enum member `dplug.vst.translatesdk.DEPRECATED_effFlagsCanMono` at ../../vst/dplug/vst/translatesdk.d-mixin-14(62,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(171,4): Error: enum member `dplug.vst.translatesdk.DEPRECATED_effFlagsExtIsAsync` conflicts with enum member `dplug.vst.translatesdk.DEPRECATED_effFlagsExtIsAsync` at ../../vst/dplug/vst/translatesdk.d-mixin-14(63,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(172,4): Error: enum member `dplug.vst.translatesdk.DEPRECATED_effFlagsExtHasBuffer` conflicts with enum member `dplug.vst.translatesdk.DEPRECATED_effFlagsExtHasBuffer` at ../../vst/dplug/vst/translatesdk.d-mixin-14(64,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(178,4): Error: enum member `dplug.vst.translatesdk.effOpen` conflicts with enum member `dplug.vst.translatesdk.effOpen` at ../../vst/dplug/vst/translatesdk.d-mixin-14(70,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(179,4): Error: enum member `dplug.vst.translatesdk.effClose` conflicts with enum member `dplug.vst.translatesdk.effClose` at ../../vst/dplug/vst/translatesdk.d-mixin-14(71,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(180,4): Error: enum member `dplug.vst.translatesdk.effSetProgram` conflicts with enum member `dplug.vst.translatesdk.effSetProgram` at ../../vst/dplug/vst/translatesdk.d-mixin-14(72,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(181,4): Error: enum member `dplug.vst.translatesdk.effGetProgram` conflicts with enum member `dplug.vst.translatesdk.effGetProgram` at ../../vst/dplug/vst/translatesdk.d-mixin-14(73,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(182,4): Error: enum member `dplug.vst.translatesdk.effSetProgramName` conflicts with enum member `dplug.vst.translatesdk.effSetProgramName` at ../../vst/dplug/vst/translatesdk.d-mixin-14(74,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(183,4): Error: enum member `dplug.vst.translatesdk.effGetProgramName` conflicts with enum member `dplug.vst.translatesdk.effGetProgramName` at ../../vst/dplug/vst/translatesdk.d-mixin-14(75,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(184,4): Error: enum member `dplug.vst.translatesdk.effGetParamLabel` conflicts with enum member `dplug.vst.translatesdk.effGetParamLabel` at ../../vst/dplug/vst/translatesdk.d-mixin-14(76,4)
../../vst/dplug/vst/translatesdk.d-mixin-14(185,4): Error: enum member `dplug.vst.translatesdk.effGetParamDisplay` conflicts with enum member `dplug.vst.translatesdk.effGetParamDisplay` at ../../vst/dplug/vst/translatesdk.d-mixin-14(77,4)
/opt/hostedtoolcache/dc/ldc2-1.24.0/x64/ldc2-1.24.0-linux-x86_64/bin/ldc2 failed with exit code 1.
```

**Comment by p0nce** [comment]
The envvar VST2_SDK must point to a directory that contains: 
`pluginterfaces/vst2.x/aeffect.h`
and
`pluginterfaces/vst2.x/aeffectx.h`

**Comment by p0nce** [comment]
> Is it because the official link (VST3_SDK 2016) includes an old version of the required file?

No, I tested it and our pseudo-parsing works.

**Comment by aminya** [comment]
> The envvar VST2_SDK must point to a directory that contains:
> `pluginterfaces/vst2.x/aeffect.h`
> and
> `pluginterfaces/vst2.x/aeffectx.h`

I guess it does:
https://github.com/aminya/Dplug/blob/3189711ddd0152e9893e319e4326a8c6c7eacb4f/.github/workflows/ci.yml#L82

**Comment by aminya** [comment]
Oh. I think I remembered the issue. We should probably make `${{ env.VST2_SDK }` a system environment variable (rather just a GitHub variable).

**Comment by p0nce** [comment]
Is it some kind of cache thing? Perhaps `dub --force` might help. I really have no idea.

**Comment by aminya** [comment]
> Oh. I think I remembered the issue. We should probably make `${{ env.VST2_SDK }` a system environment variable (rather just a GitHub variable).

This was not the issue 🤔 

> Is it some kind of cache thing? Perhaps dub --force might help. I really have no idea.

No. The caching does not happen until the builds become stable and everything successfully finishes.

**Comment by p0nce** [comment]
The error message makes it seem the mixin has been mixed in twice. But I don't see how that could happen.

**Comment by p0nce** [comment]
Probably you're using a more recent _compiler_

**Comment by aminya** [comment]
> Probably you're using a more recent _compiler_ and that will break for me too.

We are using ldc latest (1.2.4). 
https://github.com/aminya/Dplug/runs/1760997430?check_suite_focus=true#step:6:11

I am going to try to run the scripts offline to see what is going on. That gives a better insight into the issue.

**Comment by p0nce** [comment]
Seems to me the VST2 SDK is installed after dplug-build is built, this won't work.

**Comment by aminya** [comment]
The same error:
https://github.com/aminya/Dplug/runs/1761055250?check_suite_focus=true#step:10:22

**Comment by p0nce** [comment]
Found it, unfortunate typo here:
`cp "./VST3 SDK/pluginterfaces/vst2.x/aeffect.h" /home/runner/work/Dplug/Dplug/VST2_SDK/pluginterfaces/vst2.x/aeffectx.h`

Should be:
`cp "./VST3 SDK/pluginterfaces/vst2.x/aeffectx.h" /home/runner/work/Dplug/Dplug/VST2_SDK/pluginterfaces/vst2.x/aeffectx.h`

**Comment by aminya** [comment]
That was my bad 😄 It now goes to the next step. Some errors to fix, but not as cryptic any more

https://github.com/aminya/Dplug/runs/1761131156?check_suite_focus=true

**Comment by p0nce** [comment]
Ha fixing the CI is always annoying like that ^^

**Comment by aminya** [comment]
This is ready to go! 😃

**Comment by p0nce** [comment]
A big thank you for your work! This is quite the task.
I see that you are a student; if you need funding for this or that Dplug issue, in the future do not hesitate to ask in advance.

**Comment by aminya** [comment]
You are welcome! Thank you for the support and the kind words.
